global:
  num_iterations: 5
  logging_level: INFO
############################################
cr3_data:
  data_source: "/workspace/slice-monorepo/cl_cr3/cr3_data"
  preprocess_steps:
    - step1: "description of step1"
    - step2: "description of step2"
  other_config: "additional settings for CR3 data"
############################################
inference_and_embedding:
  model_path: "EleutherAI/pythia-70m"
  gpus: ["cuda:0"]
  tokenizer_config:
    padding_side: 'left'
  inference_settings:
    prompt: "Explain to me the difference between nuclear fission and fusion."
    total_inferences: 4
    temperature_range: [0.5, 1.0]
    top_p_range: [0.8, 1.0]
    max_new_tokens_range: [50, 300]
    generate_kwargs:
      do_sample: True
      num_return_sequences: 1
  embedding_settings:
    api_key: 'sk-proj-7MAfZbOm9lPY28pubTiRT3BlbkFJGgn73o5e6sVCjoTfoFAP'
    embedding_model: 'text-embedding-ada-002'
    output_file: 'results.h5'
  other_config: "additional settings for inference and embedding"
############################################
ae_analysis:
  bert_autoencoder:
    bert_model_name: 'bert-base-uncased'
    embedding_dim: 1536
    hidden_dim: 768
    lstm_units: 256
    sequence_length: 4
  training_config:
    initial_size: 20
    increment_ratio: 0.5
    max_epochs: 50000
    learning_rate: 0.0001
    test_size: 0.1
  dataloader_config:
    batch_size: 4096
    train_loader:
      shuffle: True
      num_workers: 8
      pin_memory: True
      persistent_workers: True
    test_loader:
      shuffle: False
      num_workers: 8
      pin_memory: True
      persistent_workers: True
  file_paths:
    embeddings_path: '/workspace/slice-monorepo/cl_cr3/embedding_ae_analysis/utterance_embeddings_ds1.h5'
    experiment_name: 'bert_autoencoder_experiment'
    model_save_path: 'trained_autoencoder.pth'
    config_save_path: 'config.json'
  metrics_plot:
    save_path: 'output_dir'
    filename: 'metrics.png'
  analysis_config:
    umap:
      n_neighbors: 15
      min_dist: 0.1
      metric: 'euclidean'
    kmeans:
      n_clusters: 10
      random_state: 42
    pca:
      n_components: 2
  random_state: 42
############################################
dataset_creation:
  ratio_of_datatypes:
    type1: 0.5
    type2: 0.3
    type3: 0.2
  selection_criteria: "criteria for selecting data"
  other_config: "additional settings for dataset creation"
############################################
training:
  TARGET_NAME: "LAURA"
  FOLDER_PATH: "/workspace/slice-monorepo/cl_cr3/aligneddata"
  MODEL_NAME: "EleutherAI/pythia-70m"
  EPOCHS: 2
  BATCH_SIZE: 30
  LEARNING_RATE: 1e-4
  RATIO: 0.5
  SAVE_FOLDER: "results"
  max_length: 1000
############################################
testing:
  test_set_path: "/workspace/slice-monorepo/cl_cr3/test_set"
  metrics:
    - accuracy
    - precision
    - recall
  repeat_inference: True
  other_config: "additional settings for testing and analysis"
